---
- ovftool:
    ovftool_path: '{{ ovftool_path | default() }}'
    vcenter: '{{ vcenter | default() }}'
    vcenter_user: '{{ vcenter_user | default() }}'
    vcenter_password: '{{ vcenter_password | default() }}'
    datacenter: '{{ datacenter | default() }}'
    cluster: '{{ cluster | default() }}'
    datastore: '{{ datastore | default() }}'
    portgroup: '{{ portgroup | default() }}'
    vm_name: '{{ vm_name | default() }}'
    path_to_ova: '{{ path_to_ova | default() }}'
    ova_file: '{{ ova_file | default() }}'
    power_on: '{{ power_on | default() }}'
    ssl_verify: '{{ ssl_verify | default() }}'
    vm_password_key: '{{ vm_password_key | default() }}'
    vm_password: '{{ vm_password | default() }}'
    props: '{{ props | default (dict()) }}'
    deployment_option: '{{ deployment_option | default() }}'
    ovf_network_name: '{{ ovf_network_name | default() }}'
    debug_opts: '{{ debug_opts | default() }}'
    vcenter_folder: '{{ vcenter_folder | default() }}'
